library(ResistanceGA)
library(raster)
library(sp) 

# Load SDM raster generated by MaxEnt
sdm.r <- raster("./examples/resis_surface/alboobliquatus.asc")

# Load coordinates
coords <- read.csv("./examples/GPS.csv", row.names = 1)  # columns: Populations, Longitude, Latitude
coords.m <- as.matrix(coords[c("Longitude", "Latitude")])
longitude <- coords$Longitude
latitude <- coords$Latitude
coords.sp <- SpatialPoints(cbind(longitude, latitude))

# Load genetic distances
gen <- read.csv("./examples/Fst.csv", row.names = 1)
gen.dist <- as.matrix(as.dist(gen))

# Optimization using ResistanceGA
wd <- paste0(getwd(), "/examples/resis_surface/")
GA.input <- GA.prep(ASCII.dir = sdm.r, Results.dir = wd,
                    pcrossover = 0.95, pmutation = 0.5, maxiter = 60,
                    parallel = 4)
gdist.input <- gdist.prep(n.Pops = length(coords.sp),
                          samples = coords.sp,
                          response = lower(gen.dist),
                          method = 'costDistance') # Optimize using least cost path distance

SS_optim(gdist.inputs = gdist.input, GA.inputs = GA.input)

# Add column and row names to the output CSV file
GA.output <- read.csv("./examples/resis_surface/Results/alboobliquatus_costDistance_distMat.csv", header = FALSE)
GA.output.m <- as.matrix(GA.output)
rownames(GA.output.m) <- rownames(coords.m)
colnames(GA.output.m) <- rownames(coords.m)
GA.output.m[upper.tri(GA.output.m)] <- ""
write.table(GA.output.m,
            file = "./examples/resis_surface/Results/alboobliquatus_resis_dist.csv",
            sep = ",", row.names = TRUE, col.names = NA, quote = FALSE)
